#! /bin/sh 

LJ_DIR=../../../src/cpp/interactions/lennard_jones_inline

OPT="-O2"

CPP=g++
$CPP -c $OPT lj_test.cpp -I$LJ_DIR
$CPP -c $OPT Particle.cpp
cd ../../../src/cpp/interactions/lennard_jones/
$CPP -c $OPT LennardJonesInteraction.cpp
cd -
$CPP lj_test.o Particle.o $LJ_DIR/LennardJonesInteraction.o -o lj_test
