import espresso

def pdbwrite(file, system):
  file = open(file,'a')
  s = "REMARK generated by Espresso\n"
  file.write(s)
  mp = 10
  #mp = max_part()
  count = 0
  while count <= mp:
    particle = system.storage.getParticle(count)

    if particle.pos:
      type = particle.type
      print 1, particle 
      st = "ATOM %6d  FE  UNX F%4d    %8.3f%8.3f%8.3f  0.00  0.00      T%03d\n"%(count, count, particle.pos[0], particle.pos[1],particle.pos[2], type)
      file.write(st)
    count +=1
  file.write('END')
  print 'done'

def psfwrite(file, system):
  file = open(file,'a')
  nParticle = int(espresso.analysis.NPart(system).compute)
  file.write("%d !NATOM"%(nParticle))
  mp = 10
  #mp = max_part()
  count = 0
  while count <= mp:
    particle = system.storage.getParticle(count)
    if particle.pos:
      type = particle.type
      file.write("%d\tT%03d\t%d UNX FE FE\n"%(count, type, count, particle.pos[0], particle.pos[1],particle.pos[2], type))
    count +=1
  bonds = []
  file.write("%d !BOND"%(len(bonds)))
  for i in range(bonds):
        file.write("%d\t%d\t"%(bond[0], bond[1]))
        if (i%4==0 and i!=0) or i==len(bonds)-1:
          file.write('\n')
  print 'done'
